//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.BagCategoryService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BagCategory", Namespace="http://schemas.datacontract.org/2004/07/WCF.Entities")]
    [System.SerializableAttribute()]
    public partial class BagCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CateNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bagCIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CateName {
            get {
                return this.CateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CateNameField, value) != true)) {
                    this.CateNameField = value;
                    this.RaisePropertyChanged("CateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bagCID {
            get {
                return this.bagCIDField;
            }
            set {
                if ((object.ReferenceEquals(this.bagCIDField, value) != true)) {
                    this.bagCIDField = value;
                    this.RaisePropertyChanged("bagCID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BagCategoryService.IWCFBagCategoryService")]
    public interface IWCFBagCategoryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFBagCategoryService/getAllCategories", ReplyAction="http://tempuri.org/IWCFBagCategoryService/getAllCategoriesResponse")]
        WebMVC.BagCategoryService.BagCategory[] getAllCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFBagCategoryService/getAllCategories", ReplyAction="http://tempuri.org/IWCFBagCategoryService/getAllCategoriesResponse")]
        System.Threading.Tasks.Task<WebMVC.BagCategoryService.BagCategory[]> getAllCategoriesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFBagCategoryServiceChannel : WebMVC.BagCategoryService.IWCFBagCategoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFBagCategoryServiceClient : System.ServiceModel.ClientBase<WebMVC.BagCategoryService.IWCFBagCategoryService>, WebMVC.BagCategoryService.IWCFBagCategoryService {
        
        public WCFBagCategoryServiceClient() {
        }
        
        public WCFBagCategoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFBagCategoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFBagCategoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFBagCategoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebMVC.BagCategoryService.BagCategory[] getAllCategories() {
            return base.Channel.getAllCategories();
        }
        
        public System.Threading.Tasks.Task<WebMVC.BagCategoryService.BagCategory[]> getAllCategoriesAsync() {
            return base.Channel.getAllCategoriesAsync();
        }
    }
}
