//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BagTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BagTBL()
        {
            this.OrderDetailTBLs = new HashSet<OrderDetailTBL>();
        }
    
        public string bagID { get; set; }
        public string bagName { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public string origin { get; set; }
        public string size { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string bagCID { get; set; }
    
        public virtual CategoryTBL CategoryTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailTBL> OrderDetailTBLs { get; set; }
    }
}
