<?xml version="1.0" encoding="utf-8"?><Database Name="BagStore" Class="DBContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=SE141133;Initial Catalog=BagStore;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BagStoreConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.BagTBL" Member="BagTBLs">
    <Type Name="BagTBL">
      <Column Name="bagID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="bagName" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="image" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="origin" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="size" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="createDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="bagCID" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="BagTBL_OrderDetailTBL" Member="OrderDetailTBLs" ThisKey="bagID" OtherKey="bagID" Type="OrderDetailTBL" />
      <Association Name="CategoryTBL_BagTBL" Member="CategoryTBL" ThisKey="bagCID" OtherKey="bagCID" Type="CategoryTBL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CategoryTBL" Member="CategoryTBLs">
    <Type Name="CategoryTBL">
      <Column Name="bagCID" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Association Name="CategoryTBL_BagTBL" Member="BagTBLs" ThisKey="bagCID" OtherKey="bagCID" Type="BagTBL" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDetailTBL" Member="OrderDetailTBLs">
    <Type Name="OrderDetailTBL">
      <Column Name="orderDetailID" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="orderID" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="bagID" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="BagTBL_OrderDetailTBL" Member="BagTBL" ThisKey="bagID" OtherKey="bagID" Type="BagTBL" IsForeignKey="true" />
      <Association Name="OrderTBL_OrderDetailTBL" Member="OrderTBL" ThisKey="orderID" OtherKey="orderID" Type="OrderTBL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderTBL" Member="OrderTBLs">
    <Type Name="OrderTBL">
      <Column Name="orderID" Type="System.String" DbType="VarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="paymentMethod" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="dateOrder" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="total" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="OrderTBL_OrderDetailTBL" Member="OrderDetailTBLs" ThisKey="orderID" OtherKey="orderID" Type="OrderDetailTBL" />
      <Association Name="AccountTBL_OrderTBL" Member="AccountTBL" ThisKey="username" OtherKey="username" Type="AccountTBL" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AccountTBL" Member="AccountTBLs">
    <Type Name="AccountTBL">
      <Column Name="username" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="phoneNumber" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="fullName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="role" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="AccountTBL_OrderTBL" Member="OrderTBLs" ThisKey="username" OtherKey="username" Type="OrderTBL" />
    </Type>
  </Table>
</Database>