//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BagStoreEntities : DbContext
    {
        public BagStoreEntities()
            : base("name=BagStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountTBL> AccountTBLs { get; set; }
        public virtual DbSet<BagTBL> BagTBLs { get; set; }
        public virtual DbSet<CategoryTBL> CategoryTBLs { get; set; }
        public virtual DbSet<OrderDetailTBL> OrderDetailTBLs { get; set; }
        public virtual DbSet<OrderTBL> OrderTBLs { get; set; }
    }
}
