//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTBL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderTBL()
        {
            this.OrderDetailTBLs = new HashSet<OrderDetailTBL>();
        }
    
        public string orderID { get; set; }
        public string username { get; set; }
        public string paymentMethod { get; set; }
        public Nullable<System.DateTime> dateOrder { get; set; }
        public Nullable<decimal> total { get; set; }
        public string status { get; set; }
    
        public virtual AccountTBL AccountTBL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailTBL> OrderDetailTBLs { get; set; }
    }
}
