//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailTBL
    {
        public string orderDetailID { get; set; }
        public string orderID { get; set; }
        public string bagID { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual BagTBL BagTBL { get; set; }
        public virtual OrderTBL OrderTBL { get; set; }
    }
}
